# Numpy Code

In [1]:
import numpy as np

**生成数组**

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3,4])
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

**数组维度的元组**

In [240]:
print(a.shape)
print(b.shape)
print(c.shape)
print(c.dtype)

(2, 3)
(4,)
(2, 2, 3)
int32


**数组的维数**

In [16]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

2
1
3


**数组的元素数量**

In [25]:
print(a.size)
print(b.size)
print(c.size)

6
4
12


**一个数组元素的字节长度**

In [19]:
print(a)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
4


**数组元素的类型**

In [20]:
print(a)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
int32


**指定数组类型**

In [23]:
d = np.array([1,2,3],dtype=np.float32)
print(d)
print(d.dtype)

[1. 2. 3.]
float32


**生成01数组**

In [26]:
np.ones([4,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
np.ones([3,2,4],np.int8) # 3个2行4列的2维数组构成的3维数组

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [30]:
np.ones([1,2])

array([[1., 1.]])

In [31]:
np.zeros([3,2,4],np.int8)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [34]:
print(a)

[[1 2 3]
 [4 5 6]]


In [33]:
print(np.ones_like(a,np.float32))

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
print(np.zeros_like(a))

[[0 0 0]
 [0 0 0]]


**数组的深浅拷贝**

In [47]:
print(a)

[[1 2 3]
 [4 5 6]]


In [37]:
a0 = np.array(a) # 新建

In [38]:
print(a0)
print(a0==a)

[[ True  True  True]
 [ True  True  True]]


In [40]:
print(a0 is a)

False


In [48]:
a1 = np.asarray(a) # 索引
print(a1)
print(a1==a)
print(a1 is a)
a1[0,0] = 9
print(a)

[[1 2 3]
 [4 5 6]]
[[ True  True  True]
 [ True  True  True]]
True
[[9 2 3]
 [4 5 6]]


**生成固定范围数组**

In [185]:
print(np.arange(10))
print(np.arange(10).reshape(1,-1)) # 转为二维数组
print(np.arange(10).reshape(-1,1,5)) # 转为三维数组

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


**等间隔数组**

In [186]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
 np.linspace(0,110,6,endpoint=1) # 起始 终止 等间隔样例数量 是否包含起始终止(默认true)

array([  0.,  22.,  44.,  66.,  88., 110.])

In [55]:
np.linspace(0,100,11) 

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**等差数组**

In [56]:
np.arange(10, 50, 2) # np.arange(start,stop, step, dtype)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

**等比数组**

In [57]:
np.logspace(0, 2, 3) # np.logspace(start,stop, num)

array([  1.,  10., 100.])

**随机数组**
**正态分布**

In [61]:
np.random.randn(3) # np.random.randn(d0, d1, …, dn) 从标准正态分布中返回一个或多个样本值

array([-1.58278352, -1.22824901, -1.73810297])

In [63]:
np.random.randn(2,3)

array([[ 1.45734793, -0.26869562, -1.29498974],
       [ 0.01314812,  0.35252312,  0.61491474]])

In [64]:
np.random.normal(5,1.2,(2,3))# np.random.normal(loc=0.0, scale=1.0, size=None) 均值 标准差 大小

array([[5.6650171 , 4.60778785, 6.45880499],
       [4.67182236, 5.03771782, 5.54806319]])

In [65]:
np.random.normal()

-0.4643522522001784

**随机数组**
**均匀分布**

In [66]:
np.random.rand(3)# np.random.rand(d0, d1, ..., dn) [0.0，1.0)内的一组均匀分布的数

array([0.76342996, 0.00906629, 0.27568076])

In [67]:
# np.random.randint(low, high=None, size=None, dtype='l')
# 从一个均匀分布中随机采样，生成一个整数或N维整数数组，
# 取数范围：若high不为None时，取[low,high)之间随机整数，否则取值[0,low)之间随机整数。
np.random.randint(3)

2

In [68]:
np.random.randint(-3,7,(2,3))

array([[-3, -2,  2],
       [ 0,  1, -2]])

In [69]:
np.random.uniform()# np.random.uniform(low=0.0, high=1.0, size=None) 从一个均匀分布[low,high)中随机采样

0.3650120220111588

In [71]:
np.random.uniform(1,2,(2,3,1))

array([[[1.89630301],
        [1.31614857],
        [1.36316608]],

       [[1.73281475],
        [1.38368307],
        [1.68603794]]])

**数组索引与切片**

In [84]:
n = np.array([[2,3,1,8],[6,5,7,4]])
print(n[0])
print(n[0][0])
print(n[0,1:3]) # [1,3)
print(n[1,:]) # 第1行
print(n[:,2]) # 第2列
print(n[:,:]) # all

[2 3 1 8]
2
[3 1]
[6 5 7 4]
[1 7]
[[2 3 1 8]
 [6 5 7 4]]


In [91]:
n1 = np.array([ [[1,2,3],[4,5,6]], [[12,3,34],[9,8,7]]])
print(n1[0,0,1])
print(n1[:,1,1]) # 2个二维的第1行第1列数字

2
[5 8]


In [188]:
n1

array([[ 1,  2,  3,  4,  5,  6],
       [12,  3, 34,  9,  8,  7]])

In [194]:
print(n1[1:4,:]) # 从索引[1]开始，切到索引[4]之前
print(n1[1:,2:]) # 从索引[1]开始，切到结尾
print(n1[:2,1:4]) # 从数组开头开始，切到索引[4]之前

[[12  3 34  9  8  7]]
[[34  9  8  7]]
[[ 2  3  4]
 [ 3 34  9]]


In [199]:
n1.resize(12)
print(n1)
print(n1[2:-2]) # 切除开头 2 个和结尾 2 个
print(n1[2:]) # 切除开头 2 个
print(n1[:-2]) # 切除结尾 2 个

[ 1  2  3  4  5  6 12  3 34  9  8  7]
[ 3  4  5  6 12  3 34  9]
[ 3  4  5  6 12  3 34  9  8  7]
[ 1  2  3  4  5  6 12  3 34  9]


In [201]:
print(n1)
print(n1[::2]) # 每 2 个元素采样一次
print(n1[::3]) # 每 3 个元素采样一次
print(n1[1:-1:2]) # 切除一头一尾后，每 2 个元素采样一次

[ 1  2  3  4  5  6 12  3 34  9  8  7]
[ 1  3  5 12 34  8]
[ 1  4 12  9]
[2 4 6 3 9]


In [204]:
e = np.arange(1,21).reshape(4,5)
print(e[1:3,1:-1]) 
print(e[::3,::2]) 
print(e[2,:]) # 提取第 2 行
print(e[1:3,:]) # 提取 1 至 2 行
print(e[2]) # 简便的提取行

[[ 7  8  9]
 [12 13 14]]
[[ 1  3  5]
 [16 18 20]]
[11 12 13 14 15]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]


In [209]:
# 数组切片仅是视图
print(e)
copy = e[:3,:1].copy() # 备份切片为新变量
print(copy.shape)
copy[1][0]=9
print(copy)
print(e[:3,:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(3, 1)
[[ 1]
 [ 9]
 [11]]
[[ 1]
 [ 6]
 [11]]


**翻转**

In [210]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
np.flipud(np.arange(10)) # 向量翻转

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [212]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [213]:
np.fliplr(np.arange(1,21).reshape(4,5)) # 左右翻转

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

In [214]:
np.flipud(np.arange(1,21).reshape(4,5)) # 上下翻转

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [215]:
np.concatenate( [ np.array([1,2,3]),np.array([4,5,6]) ] )# 向量拼接

array([1, 2, 3, 4, 5, 6])

In [216]:
# 矩阵拼接
A = np.array( [[1,2,3],[ 4,5,6]] )
B = np.array( [[7,8,9],[10,11,12]] )
print(np.concatenate( [A,B] )) # axis=0 按行拼接
print(np.concatenate( [A,B], axis=1 )) # axis=1 按列拼接

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**分裂**

In [217]:
 np.split( np.arange(10,100,10) , [2,8] ) # 在索引[2]和索引[8]的位置截断

[array([10, 20]), array([30, 40, 50, 60, 70, 80]), array([90])]

In [218]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [221]:
# 按第一个维度（行）分裂
# 默认参数 axis=0
print( np.split(np.arange(1,9).reshape(2,4),[1])) # 注意输出的是矩阵

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [227]:
# 按第二个维度（列）分裂
print( np.split( np.arange(1,9).reshape(2,4) , [1,3] , axis=1 ))

[array([[1],
       [5]]), array([[2, 3],
       [6, 7]]), array([[4],
       [8]])]


**修改形状**

In [92]:
n1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12,  3, 34],
        [ 9,  8,  7]]])

In [93]:
n1.reshape([2,6]) # 返回一个具有相同数据域

array([[ 1,  2,  3,  4,  5,  6],
       [12,  3, 34,  9,  8,  7]])

In [95]:
n1.reshape(-1) # -1: 表示通过待计算

array([ 1,  2,  3,  4,  5,  6, 12,  3, 34,  9,  8,  7])

In [111]:
n1.reshape([-1,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [12,  3],
       [34,  9],
       [ 8,  7]])

In [113]:
n1.resize((2,6))
print(n1)
print(n1.shape)

[[ 1  2  3  4  5  6]
 [12  3 34  9  8  7]]
(2, 6)


**置换**

In [114]:
print(n1)

[[ 1  2  3  4  5  6]
 [12  3 34  9  8  7]]


In [115]:
print(n1.T)

[[ 1 12]
 [ 2  3]
 [ 3 34]
 [ 4  9]
 [ 5  8]
 [ 6  7]]


In [121]:
print(n1.dtype)
print(n1.astype(np.float32),n1.astype(np.float32).dtype)

int32
[[ 1.  2.  3.  4.  5.  6.]
 [12.  3. 34.  9.  8.  7.]] float32


In [122]:
n1.tobytes()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x0c\x00\x00\x00\x03\x00\x00\x00"\x00\x00\x00\t\x00\x00\x00\x08\x00\x00\x00\x07\x00\x00\x00'

**去重**

In [128]:
n2 = np.array([[1,1,2,3],[2,4,3,7]])

In [130]:
np.unique(n2)

array([1, 2, 3, 4, 7])

**运算**

In [131]:
score = np.random.randint(40, 100, (10, 5)) # 生成10名同学，5门功课的数据

In [132]:
test_score = score[6:, 0:5] # 取出最后4名同学的成绩，用于逻辑判断

In [133]:
test_score

array([[89, 43, 63, 88, 83],
       [94, 87, 66, 87, 88],
       [90, 85, 62, 99, 74],
       [40, 48, 80, 57, 78]])

In [134]:
test_score > 60

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True, False,  True]])

In [135]:
test_score[test_score > 60] = 1

In [136]:
test_score

array([[ 1, 43,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [40, 48,  1, 57,  1]])

**判断函数**

In [137]:
np.all(test_score>0) # 是否所有

True

In [237]:
print( (test_score < 4) | (test_score > 6) )

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [139]:
np.any(test_score[0,:]==0) # 是否有一个

False

In [142]:
temp = test_score[:2,:3]
temp

array([[ 1, 43,  1],
       [ 1,  1,  1]])

In [143]:
np.where(temp == 1, 2, 0) # 判断条件，是，否

array([[2, 0, 2],
       [2, 2, 2]])

In [145]:
# 成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(score > 60, score < 90), 1, 0)

# 成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(score > 90, score < 60), 1, 0)

array([[1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**统计运算**

In [153]:
s = np.random.randint(1,15,10)
print(s)

[ 9 13 13  4  5 12 14 12 14 11]


In [157]:
print(np.max(s))
print(np.argmax(s))
print(np.min(s))
print(np.argmin(s))
print(np.mean(s)) # 平均
print(np.std(s))

14
6
4
3
10.7
3.4073450074801643


In [158]:
s1 = np.random.randint(1,15,(3,5))

In [159]:
s1

array([[ 1,  2, 10,  7,  5],
       [ 4, 12,  5,  2, 14],
       [ 3,  8,  5,  5,  9]])

In [160]:
print(np.max(s1,1)) # axis=1 行

[10 14  9]


In [161]:
print(np.max(s1,0)) # axis=0 列

[ 4 12 10  7 14]


In [163]:
print(np.argmax(s1,1)) # 行下标

[2 4 4]


**数组与数的运算**

In [164]:
s1

array([[ 1,  2, 10,  7,  5],
       [ 4, 12,  5,  2, 14],
       [ 3,  8,  5,  5,  9]])

In [165]:
s1 + 100

array([[101, 102, 110, 107, 105],
       [104, 112, 105, 102, 114],
       [103, 108, 105, 105, 109]])

In [167]:
s1 + 100 / 2

array([[51., 52., 60., 57., 55.],
       [54., 62., 55., 52., 64.],
       [53., 58., 55., 55., 59.]])

**数组运算**

In [230]:
print( np.arange(-1,-9,-1).reshape(2,4))
print( np.abs(np.arange(-1,-9,-1).reshape(2,4))) # 绝对值np.abs()
print( np.arange(-1,-9,-1).reshape(2,4) *  np.arange(-1,-9,-1).reshape(2,4))

[[-1 -2 -3 -4]
 [-5 -6 -7 -8]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  4  9 16]
 [25 36 49 64]]


In [229]:
print( np.arange(-1,-9,-1).reshape(2,4) -  np.arange(-1,-9,-1).reshape(2,4))

[[0 0 0 0]
 [0 0 0 0]]


**内置函数**

In [231]:
# 三角函数
theta = np.arange(3) * np.pi / 2
sin_v = np.sin(theta)
cos_v = np.cos(theta)
tan_v = np.tan(theta)
print( '原数组是：' , theta )
print( '正弦值是：' , sin_v )
print( '余弦值是：' , cos_v )
print( '正切值是：' , tan_v )

原数组是： [0.         1.57079633 3.14159265]
正弦值是： [0.0000000e+00 1.0000000e+00 1.2246468e-16]
余弦值是： [ 1.000000e+00  6.123234e-17 -1.000000e+00]
正切值是： [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [232]:
# 指数函数
x = np.arange(1,4)
print( 'x =' , x )
print( 'e^x =' , np.exp(x) )
print( '2^x =' , 2**x )
print( '10^x = ' , 10**x )

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2 4 8]
10^x =  [  10  100 1000]


In [233]:
# 对数函数
x = np.array( [1,10,100,1000] )
print( 'x =' , x )
print( 'ln(x) =' , np.log(x) )
print( 'log2(x) =' , np.log(x) / np.log(2) )
print( 'log10(x) =' , np.log(x) / np.log(10) )

x = [   1   10  100 1000]
ln(x) = [0.         2.30258509 4.60517019 6.90775528]
log2(x) = [0.         3.32192809 6.64385619 9.96578428]
log10(x) = [0. 1. 2. 3.]


**求和求积**

In [236]:
print(np.arange(10).reshape(2,5))
print( '按维度一求和：' , np.sum(np.arange(10).reshape(2,5),axis=0) ) # axis=0 行 axis=1 列
print( '按维度二求和：' , np.sum(np.arange(10).reshape(2,5),axis=1) )
print( '整体求和：' , np.sum(np.arange(10).reshape(2,5)) )
print( '按维度一求积：' , np.prod(np.arange(10).reshape(2,5),axis=0) )
print( '按维度二求积：' , np.prod(np.arange(10).reshape(2,5),axis=1) )
print( '整体求积：' , np.prod(np.arange(10).reshape(2,5)) )
print( '按维度一求平均：' , np.mean(np.arange(10).reshape(2,5),axis=0) )
print( '按维度二求平均：' , np.mean(np.arange(10).reshape(2,5),axis=1) )
print( '整体求平均：' , np.mean(np.arange(10).reshape(2,5)) )

[[0 1 2 3 4]
 [5 6 7 8 9]]
按维度一求和： [ 5  7  9 11 13]
按维度二求和： [10 35]
整体求和： 45
按维度一求积： [ 0  6 14 24 36]
按维度二求积： [    0 15120]
整体求积： 0
按维度一求平均： [2.5 3.5 4.5 5.5 6.5]
按维度二求平均： [2. 7.]
整体求平均： 4.5


**矩阵形状**

In [168]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape

(4, 1)

In [169]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [170]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

**矩阵乘法**

In [171]:
arr1

array([[0],
       [1],
       [2],
       [3]])

In [174]:
arr3 = arr1.T
print(arr3)

[[0 1 2 3]]


In [175]:
np.matmul(arr1,arr3)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [176]:
np.dot(arr1,arr3)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

**布尔掩码**

若一个普通数组和一个布尔型数组的维度相同，可以将布尔型数组作为普通数组的掩码，这样可以对普通数组中的元素作筛选

In [241]:
# 创建数组
arr = np.arange(1,13).reshape(3,4)
print(arr)
# 数组与数字作比较
print( arr > 4 )
# 筛选出 arr > 4 的元素
print( arr[ arr > 4 ] )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]


In [242]:
# 创建同维数组
arr1 = np.arange(1,10)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)
# 同维度数组作比较
print( arr1 > arr2)
# 筛选出 arr1 > arr2 位置上的元素
print( arr1[ arr1 > arr2 ] )
print( arr2[ arr1 > arr2 ] )

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[False False False False False  True  True  True  True]
[6 7 8 9]
[4 3 2 1]
